import Foundation
import Testing

@testable import MatrixKitCrypto

/// Fixtures generated by an independent Python reference implementation
/// (`InteropFixtures/generate_ssss_vectors.py`, transcribing the spec;
/// its HKDF matches RFC 5869 vectors and its AES-CTR matches OpenSSL)
/// from storage key `01…20`. Swift must decrypt the reference
/// ciphertexts — this is the cross-implementation interop check for the
/// 4S wire format.
@Suite("Secret storage crypto")
struct SecretStorageCryptoTests {
    private var storageKey: Data {
        var key = Data()
        for byte in 1...32 { key.append(UInt8(byte)) }
        return key
    }

    private func b64(_ string: String) -> Data {
        Primitives.base64UnpaddedDecode(string)!
    }

    @Test("Stored key check verifies the storage key")
    func keyCheck() throws {
        let iv = b64("AQIDBAUGBwgJCgsMDQ4PEA")
        let mac = b64("TgJjZhCxTphq/K/whNeO+rBm822GI6u4kqTTcyV9YEw")
        #expect(
            SecretStorageCrypto.verifyKey(
                storageKey: storageKey, iv: iv, mac: mac))
        #expect(
            !SecretStorageCrypto.verifyKey(
                storageKey: Data(repeating: 9, count: 32), iv: iv, mac: mac))
    }

    @Test("Reference-encrypted secret decrypts")
    func decryptReference() throws {
        let decrypted = try SecretStorageCrypto.decrypt(
            ciphertext: b64("QnB3/E3nX4B9Rs2g/VIoPZUrqPV1gx1iC9YSplP9cH0"),
            mac: b64("+nzquxCc6HEHTK7Kel4hwfCs6uD5+sNXZUOB1idZ0m8"),
            iv: b64("ERITFBUWFxgZGhscHR4fIA"),
            name: "m.cross_signing.master",
            storageKey: storageKey)
        var expected = Data()
        for byte in 0xa0...0xbf { expected.append(UInt8(byte)) }
        #expect(decrypted == expected)
    }

    @Test("Tampered MAC or ciphertext is rejected")
    func tamperRejected() throws {
        let iv = b64("ERITFBUWFxgZGhscHR4fIA")
        var mac = b64("+nzquxCc6HEHTK7Kel4hwfCs6uD5+sNXZUOB1idZ0m8")
        mac[0] ^= 0xff
        #expect(
            throws: CryptoError.self,
            performing: {
                try SecretStorageCrypto.decrypt(
                    ciphertext: b64("QnB3/E3nX4B9Rs2g/VIoPZUrqPV1gx1iC9YSplP9cH0"),
                    mac: mac, iv: iv, name: "m.cross_signing.master",
                    storageKey: storageKey)
            })
    }

    @Test("Encrypt/decrypt round-trips and wrong-name keys fail")
    func roundTrip() throws {
        let iv = Data([9, 8, 7, 6, 5, 4, 3, 2, 1, 0, 9, 8, 7, 6, 5, 4])
        let plaintext = Data("hello 4S".utf8)
        let (ciphertext, mac) = try SecretStorageCrypto.encrypt(
            plaintext, name: "m.cross_signing.self_signing",
            storageKey: storageKey, iv: iv)
        #expect(
            try SecretStorageCrypto.decrypt(
                ciphertext: ciphertext, mac: mac, iv: iv,
                name: "m.cross_signing.self_signing", storageKey: storageKey)
                == plaintext)
        #expect(
            throws: CryptoError.self,
            performing: {
                try SecretStorageCrypto.decrypt(
                    ciphertext: ciphertext, mac: mac, iv: iv,
                    name: "m.cross_signing.master", storageKey: storageKey)
            })
    }
}
